import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Suspense, useEffect, useState } from "react";
import { getDuckConn, useDuckConn } from "../lib/useDuckConn";
import CreateTableDropzone, {
  CreateTableDropzoneResult,
} from "../components/CreateTableDropzone";
import {
  Text,
  Box,
  ChakraProvider,
  Flex,
  Heading,
  HStack,
  Spacer,
  VStack,
  useDisclosure,
} from "@chakra-ui/react";
import SqlEditor from "../components/SqlEditor";
import "react-mosaic-component/react-mosaic-component.css";
import theme from "../theme";

const Home: NextPage = () => {
  // const duckConn = useDuckConn();
  const [value, setValue] = useState<CreateTableDropzoneResult>();
  const [mounted, setMounted] = useState(false);
  const sqlEditor = useDisclosure();

  useEffect(() => {
    // Pre-load DuckDB so that datasets load faster
    getDuckConn();
    setMounted(true);
  }, []);

  useEffect(() => {
    if (value) {
      sqlEditor.onOpen();
    } else {
      sqlEditor.onClose();
    }
  }, [value]);

  if (!mounted) {
    return null;
  }
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>Duckquack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        position={"absolute"}
        direction={"column"}
        top={0}
        left={0}
        width={"100vw"}
        height={"100vh"}
      >
        <Flex
          width={"100%"}
          as={"header"}
          px={5}
          pt={5}
          mx={"auto"}
          // maxW={"6xl"}
        >
          <Flex direction={"column"}>
            <Heading fontSize="2xl">Duckquack</Heading>
            {/*More ideas: sqrescue  resql.dev */}
            <Text fontSize="xs">Drop CSV and run SQL</Text>
          </Flex>
          <Spacer />
          <a
            href="https://www.duckdb.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Flex alignItems="center" gap={2}>
              <Text>Powered by DuckDB</Text>
              <Image
                src="/duckdb.svg"
                alt="DuckDB Logo"
                width={30}
                height={30}
              />
            </Flex>
          </a>
        </Flex>

        <Flex as={"main"} w={"100vw"} height={"100%"}>
          <Flex p={5}>
            <Suspense fallback={<div>Loading…</div>}>
              <CreateTableDropzone
                value={value}
                outputColumnSpecs={[]}
                allowCustomColumns={true}
                onTableCreated={(inputTableName: string, result) => {
                  console.log(inputTableName, result);
                  setValue(result);
                }}
                onChange={(result) => {
                  console.log("onChange", result);
                }}
                onReset={() => {
                  console.log("onReset");
                }}
                onError={(message) => console.log("onError", message)}
              />
            </Suspense>
          </Flex>

          {sqlEditor.isOpen && value?.inputTableName ? (
            <SqlEditor
              tableName={value?.inputTableName}
              isOpen={true}
              onClose={console.log}
            />
          ) : null}
        </Flex>
      </Flex>
    </ChakraProvider>
  );
};

export default Home;
